---
- name: Creating users
  hosts: all
  vars_files:
  - Variables/userlist.yml
  tasks:
  - name: Creating user
    win_user:
      name: "{{item.name}}"
      state: present
    with_items: "{{users}}"