---
- name: Creating users
  hosts: all
  var_files:
  - Variables/userlist.yml
  tasks:
  - name: Creating user {{ usr }}
    win_user:
      name: "{{ usr }}"
      state: present
    loop: "{{Variables/userlist.yml}}"